baseurl = "https://blog.tkan.dev/"
title = "ggdG:wq!"
theme = "coder-portfolio"
languagecode = "ja"
defaultcontentlanguage = "ja"

googleAnalytics = "UA-89403151-6"

paginate = 20

pygmentsstyle = "b2" # Color-theme or style for syntax highlighting.
pygmentscodefences = true # Enable code fence background highlighting.
pygmentscodefencesguesssyntax = true # Enable syntax guessing for code fences without specified language.
pygmentsUseClasses = true # new add

enableRobotsTXT = true
preserveTaxonomyNames = false
pluralizeListTitles = false

[params] # theme parameters
    author = "Tkan" # Author's name.
    info = "Infrastructure Engineer" # Author's job title or info.
    description = "Tkan's personal website" # Site description.
    keywords = "Blog, config, engineering, Computer Science" # Site keywords.
    avatarurl = "images/avatar.jpg" # Contain the path of the optionnal avatar in the static folder.

    footercontent = "" # Add footer content
    fixedbarContent = "" # Add fixedbar content
    fixedbarContentAfter = "Thank You! Please share it if you like it→" # Add fixedbar content after click

    # Whether you want to hide copyright and credits in the footer.
    hideCredits = true
    hideCopyright = true

    # Custom CSS
    custom_css = []

    # Alignment of Mobile Menu items
    itemscentered = true

    # RTL support
    rtl = false

    # Bottom sns share
    snsShare = true # new add
    # Popular sns share
    # if you want add sns. please message!
    enableTwitterShare = true
    enableFacebookShare = true
    enableHatenaShare = true
    enableLineShare = false
    enableLinkedInShare = true

    thumbnail = "images/tn.png?123" # default sns thumbnail

    # Multilanguage mode
    langseparator = "|" # Separates menus from language selectors when site is multilingual.

# Social links
[[params.social]]
    name = "Github"
    icon = "fab fa-github"
    weight = 1
    url = "https://github.com/tkancf/"
[[params.social]]
    name = "Twitter"
    icon = "fab fa-twitter"
    weight = 2
    url = "https://twitter.com/tkancf/"

# Menu links
# [[menu.main]]
#     name = "Blog"
#     weight = 1
#     url  = "posts/"
# [[menu.main]]
#     name = "Tags"
#     url = "tags"
#     weight = 2
# [[menu.main]]
#     name = "About"
#     url = "about/"
#     weight = 3

[languages]
    [languages.ja]
        languagename = "Switch to Japanese" # The language name to be displayed in the selector.
        title = "ggdG:wq!"

        # You can configure the theme parameter for each language. 
        [languages.ja.params]
        author = "Tkan"
        info = "ggdG:wq! - Tkanの雑記ブログ"

        description = "Tkan's personal website"
        keywords = "blog,developer,personal"

        [languages.ja.menu] # It is possible to change the menu too.

        [[languages.ja.menu.main]]
        name = "About"
        weight = 1.0
        url = "about"

        [[languages.ja.menu.main]]
        name = "ブログ"
        weight = 2.0
        url = "posts"


    [languages.en]
        languagename = "Switch to English"
        title = "ggdG:wq!"

        [languages.en.params]
            author = "Tkan"
            description = "Tkan's personal website"
            keywords = "blog, ブログ, エンジニア"
            info = "ggdG:wq! - Tkan's blog"

        [languages.en.menu]

            [[languages.en.menu.main]]
            name = "About"
            weight = 1.0
            url = "en/about"

            [[languages.en.menu.main]]
            name = "Blog"
            weight = 2.0
            url = "en/posts"
