baseURL = "https://ggdg.tkan.dev/"
title = "ggdG:wq!"
theme = "ggdg"
languageCode = "ja"
DefaultContentLanguage = "ja"
enableInlineShortcodes = true
googleAnalytics = "UA-89403151-6"

[params]
    author = "Tkan"
    google_search = true
    description = "Tkan's blog"

[taxonomies]
    category = "categories"
    tag = "tags"
