baseURL = "https://ggdg.tkan.dev/"
title = "ggdG:wq!"
theme = "erblog"
paginate = 3
languageCode = "ja"
DefaultContentLanguage = "ja"
enableInlineShortcodes = true
footnoteReturnLinkContents = "^"
googleAnalytics = "UA-89403151-6"

[params]
    author = "tkancf"
    badge = "black"
    quote = "gray"
    portrait = "images/avatar.jpg" # Contain the path of the optionnal avatar in the static folder.
    index_posts_num = 7
    google_search = true
    logo = "images/avatar.jpg"
    description = "tkan's personal blog"
    bio = """
    <br />
    <p>Vimが好きなインフラエンジニアです。 最近はVtuberとお絵描きを趣味としています。</p>
    <br />
    <p>このブログには技術系の知見と日記を書いています。</p>
    """
    copyright = "Copyright © 2019-2020, tkancf all rights reserved."
    favicon = "images/favicon-16x16.png"

[[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 10

[taxonomies]
    category = "categories"
    tag = "tags"
#series = "series"

[[menu.icon]]
    url = "https://github.com/tkancf/"
    name = "github"
    weight = 1

[[menu.icon]]
    url = "https://twitter.com/tkancf"
    name = "twitter"
    weight = 1
